
copyright: "© 2025 Haifeng Li — Site created on August 20, 2025"

site_name: Security Products Docs
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy
    - navigation.tabs
    - navigation.tracking
    # - navigation.footer
plugins:
  - search
  - awesome-pages
  - section-index
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - codehilite
extra:
  generator: false
  social:
    - icon: material/book-open-page-variant
      link: https://lihaifeng.net/
      name: Blog   
  footer: |
    <div style="text-align: center; font-size: 0.85rem; opacity: 0.8; margin-top: 1em;">
      Site created on <strong>August 20, 2025</strong>
    </div>  
extra_css:
  - overrides/home.css 
