name: Deploy MkDocs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for creation dates)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-section-index
          fi

      - name: Normalize Windows-style image paths
        run: |
          python - <<'PY'
          import pathlib
          for p in pathlib.Path('docs').rglob('*.md'):
              s = p.read_text(encoding='utf-8')
              s2 = (s.replace('.\\assets\\','assets/')
                      .replace('.\\assets/','assets/')
                      .replace('\\assets\\','assets/')
                      .replace('\\','/'))
              if s2 != s:
                  p.write_text(s2, encoding='utf-8')
          PY

      # 生成首页“Latest Updates”（以及可选的 Archives）
      - name: Generate Home & Archives
        run: |
          if [ -f tools/gen_updates.py ]; then
            python tools/gen_updates.py --docs docs --index docs/index.md --limit 10
            if [ -f docs/archives.md ]; then
              python tools/gen_updates.py --docs docs --archives docs/archives.md
            fi
          else
            echo "tools/gen_updates.py not found, skip generation."
          fi

      - name: Build site (strict)
        run: mkdocs build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
